tft:
  - name: "Test 1"
    namespace: "default"
    # test cases can be specified individually i.e "1,2,3,6" or as a range i.e. "1-9,15-19"
    test_cases: "1"
    duration: "10"
    # Location of artifacts from run can be specified: default <working-dir>/ft-logs/
    # logs: "/tmp/ft-logs"
    connections:
      - name: "Connection 1"
        # supported types: iperf-tcp, iperf-udp
        type: "iperf-tcp"
        instances: 1
        server:
          - name: "worker-145"
            persistent: "false"
            sriov: "true"
        client:
          - name: "worker-146"
            sriov: "true"
        plugins:
          - name: capture_flows
          - name: HWOL_validation
          - name: measureCPU
